all:
	bash ../scripts/create-icns.sh exported/VirtualDeviceManager.png
	mv app.icns exported/VirtualDeviceManager.icns
# Copy files
	cp exported/VirtualDeviceManager.icns ../../../src/Manager/Resources/app.icns
