#!/bin/bash

PATH=/bin:/sbin:/usr/bin:/usr/sbin
export PATH

#
# Register Karabiner-DriverKit-VirtualHIDDeviceClient.app as a LaunchDaemon
#

'/Library/Application Support/org.pqrs/Karabiner-DriverKit-VirtualHIDDevice/Applications/Karabiner-DriverKit-VirtualHIDDeviceClient.app/Contents/MacOS/Karabiner-DriverKit-VirtualHIDDeviceClient' --service-management-register

#
# Relaunch karabiner processes
#

launchctl kickstart -k system/org.pqrs.Karabiner-DriverKit-VirtualHIDDeviceClient5

exit 0
