#!/bin/bash

PATH=/bin:/sbin:/usr/bin:/usr/sbin
export PATH

remove_files_script='/Library/Application Support/org.pqrs/Karabiner-DriverKit-VirtualHIDDevice/scripts/uninstall/remove_files.sh'
if [ -f "$remove_files_script" ]; then
  bash "$remove_files_script"
fi

exit 0
